export const GET_TEST_LIST = 'GET_TEST_LIST'
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA'
export const HAS_FACEBOOK_CONNECT = 'HAS_FACEBOOK_CONNECT'
export const FACEBOOK_VERIFY = 'FACEBOOK_VERIFY'

export const GET_USER = 'GET_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const UNSET_DETAILS_FOR_BANNED_USER = 'UNSET_DETAILS_FOR_BANNED_USER'

export const SHOW_VERFIY_INFO_POPUP = 'SHOW_VERFIY_INFO_POPUP'
export const CLOSE_VERFIY_INFO_POPUP = 'CLOSE_VERFIY_INFO_POPUP'
export const SET_EMAIL_POPUP = 'SET_EMAIL_POPUP'

export const SHOW_SET_PASSWORD_POPUP = 'SHOW_SET_PASSWORD_POPUP'
export const CLOSE_SET_PASSWORD_POPUP = 'SET_PASSWORD_POPUP'
export const IS_FROM_FORGET_PASSWORD = 'IS_FROM_FORGET_PASSWORD'
export const REMOVE_IS_FROM_FORGET_PASSWORD = 'REMOVE_IS_FROM_FORGET_PASSWORD'

export const GET_PIN_BY_PHONE = 'GET_PIN_BY_PHONE'
export const GET_PIN_BY_PHONE_SUCCESS = 'GET_PIN_BY_PHONE_SUCCESS'
export const GET_PIN_BY_PHONE_ERROR = 'GET_PIN_BY_PHONE_ERROR'

export const GET_VERIFY_PIN = 'GET_VERIFY_PIN'
export const GET_VERIFY_PIN_SUCCESS = 'GET_VERIFY_PIN_SUCCESS'
export const GET_VERIFY_PIN_ERROR = 'GET_VERIFY_PIN_ERROR'
export const GET_VERIFY_PASSWORD = 'GET_VERIFY_PASSWORD'

export const SHOW_BANNED_ERROR = 'SHOW_BANNED_ERROR'

export const SUBMIT_RAMCI = 'SUBMIT_RAMCI'
export const SUBMIT_RAMCI_SUCCESS = 'SUBMIT_RAMCI_SUCCESS'
export const SUBMIT_RAMCI_FAIL = 'SUBMIT_RAMCI_FAIL'
export const UPDATE_CONSENT_SUCCESS = 'UPDATE_CONSENT_SUCCESS'
export const UPDATE_CONSENT_FAIL = 'UPDATE_CONSENT_FAIL'
export const REMOVE_RAMCI_ERROR = 'REMOVE_RAMCI_ERROR'

export const GET_FAV_PROPERTY_LIST = 'GET_FAV_PROPERTY_LIST'
export const IS_OPEN_PLAYSTORE = 'IS_OPEN_PLAYSTORE'
export const LEARN_ITEMS = 'LEARN_ITEMS'
export const BANNER_TEXT = 'BANNER_TEXT'

export const SHOW_LOCKED_MODAL = 'SHOW_LOCKED_MODAL'

export const SERVER_ERROR = 'SERVER_ERROR'

export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const USER_LOGINED = 'USER_LOGINED'
